[package]
name = "baleine_engine_setup"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = { version = "0.9", features = ["serde"] }
